-- Techora full catalog seed. Generated from the current local catalog.
INSERT INTO products (id, name, category, price_pesos, rating, review_count, badge, image_url, description, stock_quantity) VALUES
('apple-magsafe-charger', 'Apple MagSafe Charger', 'Accessories', 2990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-magsafe-charger/900/900', 'A carefully selected Apple MagSafe Charger for your everyday technology setup.', 15),
('arc-charge', 'Arc Charge', 'Accessories', 4307, 4.5, 221, NULL, 'https://picsum.photos/seed/techora-arc-charge/900/900', 'A compact multi-device charging hub that keeps every essential powered.', 40),
('baseus-power-bank', 'Baseus Power Bank', 'Accessories', 2490, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-baseus-power-bank/900/900', 'A carefully selected Baseus Power Bank for your everyday technology setup.', 15),
('logitech-wireless-mouse', 'Logitech Wireless Mouse', 'Accessories', 1590, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-logitech-wireless-mouse/900/900', 'A carefully selected Logitech Wireless Mouse for your everyday technology setup.', 15),
('mechanical-keyboard', 'Mechanical Keyboard', 'Accessories', 4590, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-mechanical-keyboard/900/900', 'A carefully selected Mechanical Keyboard for your everyday technology setup.', 15),
('samsung-45w-charger', 'Samsung 45W Charger', 'Accessories', 2290, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-45w-charger/900/900', 'A carefully selected Samsung 45W Charger for your everyday technology setup.', 15),
('samsung-t7-ssd', 'Samsung T7 SSD', 'Accessories', 6990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-t7-ssd/900/900', 'A carefully selected Samsung T7 SSD for your everyday technology setup.', 15),
('sandisk-portable-ssd', 'SanDisk Portable SSD', 'Accessories', 5990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-sandisk-portable-ssd/900/900', 'A carefully selected SanDisk Portable SSD for your everyday technology setup.', 15),
('anker-gan-charger', 'UGREEN CD361/15570 Mini Robot 65W 3-Port PD GAN Fast Charger', 'Accessories', 1299, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-anker-gan-charger/900/900', 'A carefully selected Anker GaN Charger for your everyday technology setup.', 15),
('ugreen-usb-c-hub', 'UGREEN USB-C Hub', 'Accessories', 3490, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-ugreen-usb-c-hub/900/900', 'A carefully selected UGREEN USB-C Hub for your everyday technology setup.', 15),
('aero-pro', 'Aero Pro', 'Audio', 4049, 4.8, 156, 'Best seller', 'https://picsum.photos/seed/techora-aero-pro/900/900', 'A thin, powerful laptop engineered for deep work, creative flow, and life on the move.', 14),
('anker-soundcore-liberty', 'Anker Soundcore Liberty 4', 'Audio', 3249, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-anker-soundcore-liberty/900/900', 'A carefully selected Anker Soundcore Liberty for your everyday technology setup.', 15),
('apple-airpods-max', 'Apple AirPods Max', 'Audio', 36490, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-airpods-max/900/900', 'A carefully selected Apple AirPods Max for your everyday technology setup.', 15),
('apple-airpods-pro', 'Apple AirPods Pro 3', 'Audio', 15990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-airpods-pro/900/900', 'A carefully selected Apple AirPods Pro for your everyday technology setup.', 15),
('bose-quietcomfort-ultra', 'Bose QuietComfort Ultra', 'Audio', 24990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-bose-quietcomfort-ultra/900/900', 'A carefully selected Bose QuietComfort Ultra for your everyday technology setup.', 15),
('jbl-live-beam', 'JBL Live Beam', 'Audio', 7990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-jbl-live-beam/900/900', 'A carefully selected JBL Live Beam for your everyday technology setup.', 15),
('pulse-max', 'Pulse Max', 'Audio', 15543, 4.7, 412, 'Popular', 'https://picsum.photos/seed/techora-pulse-max/900/900', 'Immersive adaptive sound with all-day comfort and intelligent noise control.', 29),
('samsung-galaxy-buds', 'Samsung Galaxy Buds', 'Audio', 8990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-buds/900/900', 'A carefully selected Samsung Galaxy Buds for your everyday technology setup.', 15),
('sony-wf-1000xm6', 'Sony WF-1000XM6', 'Audio', 16990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-sony-wf-1000xm6/900/900', 'A carefully selected Sony WF-1000XM6 for your everyday technology setup.', 15),
('sony-wh-1000xm6', 'Sony WH-1000XM6', 'Audio', 22990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-sony-wh-1000xm6/900/900', 'A carefully selected Sony WH-1000XM6 for your everyday technology setup.', 15),
('asus-proart-monitor', 'ASUS ProArt Monitor', 'Home office', 30990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-asus-proart-monitor/900/900', 'A carefully selected ASUS ProArt Monitor for your everyday technology setup.', 15),
('dell-ultrasharp-monitor', 'Dell UltraSharp Monitor', 'Home office', 27990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-dell-ultrasharp-monitor/900/900', 'A carefully selected Dell UltraSharp Monitor for your everyday technology setup.', 15),
('halo-desk', 'Halo Desk Lamp', 'Home office', 7428, 4.6, 75, NULL, 'https://picsum.photos/seed/techora-halo-desk-lamp/900/900', 'Warm, focused light with touch controls and a beautifully minimal silhouette.', 22),
('hp-officejet-pro-printer', 'HP OfficeJet Pro Printer', 'Home office', 10990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-hp-officejet-pro-printer/900/900', 'A carefully selected HP OfficeJet Pro Printer for your everyday technology setup.', 15),
('key-01', 'Key 01', 'Home office', 8676, 4.8, 63, NULL, 'https://picsum.photos/seed/techora-key-01/900/900', 'A satisfying mechanical keyboard designed for focused, quiet productivity.', 25),
('lg-ultragear-monitor', 'LG UltraGear Monitor', 'Home office', 21990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-lg-ultragear-monitor/900/900', 'A carefully selected LG UltraGear Monitor for your everyday technology setup.', 15),
('logitech-brio-4k', 'Logitech Brio 4K', 'Home office', 10990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-logitech-brio-4k/900/900', 'A carefully selected Logitech Brio 4K for your everyday technology setup.', 15),
('logitech-mx-keys', 'Logitech MX Keys', 'Home office', 7990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-logitech-mx-keys/900/900', 'A carefully selected Logitech MX Keys for your everyday technology setup.', 15),
('logitech-mx-master-3s', 'Logitech MX Master 3S', 'Home office', 6990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-logitech-mx-master-3s/900/900', 'A carefully selected Logitech MX Master 3S for your everyday technology setup.', 15),
('samsung-smart-monitor', 'Samsung Smart Monitor', 'Home office', 19990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-smart-monitor/900/900', 'A carefully selected Samsung Smart Monitor for your everyday technology setup.', 15),
('acer-nitro-v', 'Acer Nitro V', 'Laptops', 52990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-acer-nitro-v/900/900', 'A carefully selected Acer Nitro V for your everyday technology setup.', 15),
('apple-macbook-air', 'Apple MacBook Air M4', 'Laptops', 102990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-macbook-air/900/900', 'A carefully selected Apple MacBook Air for your everyday technology setup.', 15),
('apple-macbook-pro', 'Apple MacBook Pro M5', 'Laptops', 139990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-macbook-pro/900/900', 'A carefully selected Apple MacBook Pro for your everyday technology setup.', 15),
('asus-tuf-gaming-a15', 'ASUS TUF Gaming A15', 'Laptops', 59990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-asus-tuf-gaming-a15/900/900', 'A carefully selected ASUS TUF Gaming A15 for your everyday technology setup.', 15),
('dell-xps-14', 'Dell XPS 14', 'Laptops', 94990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-dell-xps-14/900/900', 'A carefully selected Dell XPS 14 for your everyday technology setup.', 15),
('hp-pavilion', 'HP Pavilion', 'Laptops', 45990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-hp-pavilion/900/900', 'A carefully selected HP Pavilion for your everyday technology setup.', 15),
('lenovo-legion-5', 'Lenovo Legion 5', 'Laptops', 72990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-lenovo-legion-5/900/900', 'A carefully selected Lenovo Legion 5 for your everyday technology setup.', 15),
('lenovo-thinkpad-e16-77730', 'Lenovo ThinkPad E16', 'Laptops', 45500, 0, 0, NULL, 'https://picsum.photos/seed/techora-lenovo-thinkpad-e16-77730/900/900', 'A new Lenovo ThinkPad E16  added to the Techora catalog.', 10),
('lenovo-thinkpad-x1-carbon', 'Lenovo ThinkPad X1 Carbon', 'Laptops', 99990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-lenovo-thinkpad-x1-carbon/900/900', 'A carefully selected Lenovo ThinkPad X1 Carbon for your everyday technology setup.', 15),
('nova-x1', 'Apple Iphone 14 Pro Max', 'Smartphones', 48815, 5, 1, 'New', 'https://picsum.photos/seed/techora-nova-x1/900/900', 'Flagship performance, an edge-to-edge OLED display, and a camera that catches every detail.', 17),
('apple-iphone-17', 'Apple iPhone 17 Pro Max', 'Smartphones', 81790, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-iphone-17/900/900', 'A carefully selected Apple iPhone 17 for your everyday technology setup.', 15),
('asus-rog-phone-10', 'ASUS ROG Phone 10', 'Smartphones', 76995, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-asus-rog-phone-10/900/900', 'A carefully selected ASUS ROG Phone 10 for your everyday technology setup.', 15),
('google-pixel-10-pro', 'Google Pixel 10 Pro', 'Smartphones', 66990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-google-pixel-10-pro/900/900', 'A carefully selected Google Pixel 10 Pro for your everyday technology setup.', 15),
('nothing-phone-4', 'Nothing Phone (4)', 'Smartphones', 28990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-nothing-phone-4/900/900', 'A carefully selected Nothing Phone (4) for your everyday technology setup.', 15),
('samsung-galaxy-s26-ultra', 'Samsung Galaxy S26 Ultra', 'Smartphones', 78291, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-s26-ultra/900/900', 'A carefully selected Samsung Galaxy S26 Ultra for your everyday technology setup.', 15),
('samsung-galaxy-z-fold7', 'Samsung Galaxy Z Fold 8', 'Smartphones', 109990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-z-fold7/900/900', 'A carefully selected Samsung Galaxy Z Fold7 for your everyday technology setup.', 15),
('xiaomi-17', 'Xiaomi 17 Pro Max', 'Smartphones', 46400, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-xiaomi-17/900/900', 'A carefully selected Xiaomi 17 for your everyday technology setup.', 15),
('apple-ipad', 'Apple iPad Air M4', 'Tablets', 77990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-ipad/900/900', 'A carefully selected Apple iPad for your everyday technology setup.', 11),
('frame-mini', 'Frame Mini', 'Tablets', 29899, 4.7, 104, NULL, 'https://picsum.photos/seed/techora-frame-mini/900/900', 'A compact canvas for notes, shows, sketches, and your most important ideas.', 15),
('huawei-matepad', 'Huawei MatePad', 'Tablets', 17990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-huawei-matepad/900/900', 'A carefully selected Huawei MatePad for your everyday technology setup.', 15),
('ipad-air', 'iPad Air', 'Tablets', 37990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-ipad-air/900/900', 'A carefully selected iPad Air for your everyday technology setup.', 15),
('ipad-pro', 'iPad Pro', 'Tablets', 66990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-ipad-pro/900/900', 'A carefully selected iPad Pro for your everyday technology setup.', 15),
('lenovo-tab', 'Lenovo Tab', 'Tablets', 14990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-lenovo-tab/900/900', 'A carefully selected Lenovo Tab for your everyday technology setup.', 15),
('samsung-galaxy-tab-s11', 'Samsung Galaxy Tab S11', 'Tablets', 44990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-tab-s11/900/900', 'A carefully selected Samsung Galaxy Tab S11 for your everyday technology setup.', 15),
('samsung-galaxy-tab-s11-ultra', 'Samsung Galaxy Tab S11 Ultra', 'Tablets', 69990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-tab-s11-ultra/900/900', 'A carefully selected Samsung Galaxy Tab S11 Ultra for your everyday technology setup.', 15),
('xiaomi-pad', 'Xiaomi Pad 8', 'Tablets', 21999, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-xiaomi-pad/900/900', 'A carefully selected Xiaomi Pad for your everyday technology setup.', 15),
('apple-watch-series', 'Apple Watch Series', 'Wearables', 24990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-watch-series/900/900', 'A carefully selected Apple Watch Series for your everyday technology setup.', 15),
('apple-watch-ultra', 'Apple Watch Ultra', 'Wearables', 52990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-apple-watch-ultra/900/900', 'A carefully selected Apple Watch Ultra for your everyday technology setup.', 15),
('fitbit-charge', 'Fitbit Charge', 'Wearables', 8990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-fitbit-charge/900/900', 'A carefully selected Fitbit Charge for your everyday technology setup.', 15),
('garmin-venu', 'Garmin Venu', 'Wearables', 23990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-garmin-venu/900/900', 'A carefully selected Garmin Venu for your everyday technology setup.', 15),
('google-pixel-watch', 'Google Pixel Watch', 'Wearables', 19990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-google-pixel-watch/900/900', 'A carefully selected Google Pixel Watch for your everyday technology setup.', 15),
('huawei-watch-gt', 'Huawei Watch GT', 'Wearables', 11990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-huawei-watch-gt/900/900', 'A carefully selected Huawei Watch GT for your everyday technology setup.', 15),
('orbit-watch', 'Orbit Watch', 'Wearables', 20536, 5, 1, 'New', 'https://picsum.photos/seed/techora-orbit-watch/900/900', 'Health insights, training metrics, and a refined design that goes everywhere.', 14),
('samsung-galaxy-ring', 'Samsung Galaxy Ring', 'Wearables', 23990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-ring/900/900', 'A carefully selected Samsung Galaxy Ring for your everyday technology setup.', 15),
('samsung-galaxy-watch', 'Samsung Galaxy Watch', 'Wearables', 18990, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-samsung-galaxy-watch/900/900', 'A carefully selected Samsung Galaxy Watch for your everyday technology setup.', 15),
('xiaomi-smart-band', 'Xiaomi Smart Band 9 Active', 'Wearables', 1499, 4.6, 0, NULL, 'https://picsum.photos/seed/techora-xiaomi-smart-band/900/900', 'A carefully selected Xiaomi Smart Band for your everyday technology setup.', 15)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  price_pesos = EXCLUDED.price_pesos,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  image_url = EXCLUDED.image_url,
  description = EXCLUDED.description,
  stock_quantity = EXCLUDED.stock_quantity,
  updated_at = NOW();

