import { useEffect, useState } from 'react';
import { Field, Modal, LoadingState } from './ui';
import { money, emptyRegistration } from './lib';

export function AuthModal({ mode, close, success, switchMode }) {
  const signingUp = mode === 'signup'; const forgot = mode === 'forgot';
  const [login, setLogin] = useState({ email: localStorage.getItem('techora-remembered-email') || '', password: '' });
  const [registration, setRegistration] = useState(emptyRegistration);
  const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false); const [remember, setRemember] = useState(Boolean(localStorage.getItem('techora-remembered-email')));
  useEffect(() => { setError(''); setMessage(''); }, [mode]);
  const update = (name, value) => signingUp ? setRegistration((values) => ({ ...values, [name]: value })) : setLogin((values) => ({ ...values, [name]: value }));
  async function submit(event) {
    event.preventDefault(); setError('');
    if (forgot) { setSaving(true); try { const response = await fetch('/api/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: login.email }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setError(''); setMessage(result.message); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } return; }
    if (signingUp && registration.password !== registration.confirmPassword) return setError('Passwords do not match.');
    setSaving(true);
    try {
      const response = await fetch(signingUp ? '/api/auth/register' : '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(signingUp ? registration : login) });
      const raw = await response.text();
      let result;
      try { result = JSON.parse(raw); }
      catch { throw new Error(`The server returned an invalid response (${response.status}). Restart the backend and try again.`); }
      if (!response.ok) throw new Error(result.message || 'Something went wrong.');
      if (!signingUp) { if (remember) localStorage.setItem('techora-remembered-email', login.email); else localStorage.removeItem('techora-remembered-email'); } localStorage.setItem('techora-user', JSON.stringify(result.user)); success(result.user); close();
    } catch (requestError) { setError(requestError.message); } finally { setSaving(false); }
  }
  return <Modal close={close} className={`auth-modal ${signingUp ? 'wide' : ''}`}>
    <p className="eyebrow">{signingUp ? 'Create your account' : forgot ? 'Account recovery' : 'Welcome back'}</p>
    <h2 id="account-heading">{signingUp ? 'Shop smarter, from the start.' : forgot ? 'Reset your password.' : 'Good to see you.'}</h2><p className="modal-copy">{signingUp ? 'Save your delivery details, track orders, and check out faster.' : forgot ? 'Enter your email and we’ll prepare password reset instructions.' : 'Sign in to your Techora account.'}</p>
    {import.meta.env.VITE_DEMO === 'true' && !signingUp && !forgot && <p className="form-success" role="status">Demo access: use any email and password. Admin: <strong>admin@techora.demo</strong> / <strong>demo-admin</strong>.</p>}<form className="auth-form" onSubmit={submit}>
      {signingUp && <><div className="two-fields"><Field label="First name" value={registration.firstName} onChange={(value) => update('firstName', value)} required /><Field label="Last name" value={registration.lastName} onChange={(value) => update('lastName', value)} required /></div><div className="two-fields"><Field label="Email address" type="email" value={registration.email} onChange={(value) => update('email', value)} required /><Field label="Mobile number" type="tel" value={registration.phone} onChange={(value) => update('phone', value)} required /></div><p className="address-label">Default shipping address</p><Field label="Address line 1" value={registration.address1} onChange={(value) => update('address1', value)} required /><Field label="Address line 2 (unit, building, etc.)" value={registration.address2} onChange={(value) => update('address2', value)} /><div className="three-fields"><Field label="City / Municipality" value={registration.city} onChange={(value) => update('city', value)} required /><Field label="Province / State" value={registration.state} onChange={(value) => update('state', value)} required /><Field label="Postal code" value={registration.postalCode} onChange={(value) => update('postalCode', value)} required /></div><Field label="Country" value={registration.country} onChange={(value) => update('country', value)} required /></>}
      {!signingUp && <Field label="Email address" type="email" value={login.email} onChange={(value) => update('email', value)} required />}
      {!forgot && <Field label="Password" type="password" minLength="8" value={signingUp ? registration.password : login.password} onChange={(value) => update('password', value)} required />}{!signingUp && !forgot && <label className="checkbox"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> Remember Me</label>}
      {signingUp && <><Field label="Confirm password" type="password" minLength="8" value={registration.confirmPassword} onChange={(value) => update('confirmPassword', value)} required /><label className="checkbox"><input type="checkbox" checked={registration.marketing} onChange={(event) => update('marketing', event.target.checked)} /> Send me new products and exclusive offers.</label></>}
      {error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status">{message}</p>}<button className="button dark" disabled={saving}>{saving ? 'Please wait…' : signingUp ? 'Create account →' : forgot ? 'Send instructions →' : 'Sign in'}</button>
    </form>{!signingUp && !forgot && <button className="forgot-link" onClick={() => switchMode('forgot')}>Forgot password?</button>}<p className="switcher">{signingUp ? 'Already have an account?' : 'New to Techora?'} <button onClick={() => switchMode(signingUp ? 'login' : 'signup')}>{signingUp ? 'Sign in' : 'Create an account'}</button></p>
  </Modal>;
}

export function OrdersModal({ user, close }) {
  const [orders, setOrders] = useState([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`/api/orders?userId=${encodeURIComponent(user.id)}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); return data; }).then(setOrders).catch((reason) => setError(reason.message || 'Could not load your orders.')).finally(() => setLoading(false)); }, [user.id]);
  const steps = [{ key: 'PENDING', label: 'Order placed' }, { key: 'CONFIRMED', label: 'Confirmed' }, { key: 'PROCESSING', label: 'Processing' }, { key: 'SHIPPED', label: 'Shipped' }, { key: 'OUT_FOR_DELIVERY', label: 'Out for delivery' }, { key: 'DELIVERED', label: 'Delivered' }];
  const statusIndex = (status) => steps.findIndex((step) => step.key === status);
  const date = (value) => new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(value));
  return <Modal close={close} className="orders-modal"><p className="eyebrow">Your Techora account</p><h2 id="orders-heading">Order tracking</h2><p className="modal-copy">Track every order from confirmation to delivery.</p>{error && <p className="form-error" role="alert">{error}</p>}{loading && <LoadingState text="Loading your orders…" />}{!loading && !error && !orders.length && <p className="empty">You have not placed an order yet.</p>}{orders.map((order) => { const active = statusIndex(order.status); return <article className="order-card" key={order.id}><div className="order-head"><div><strong>{order.id}</strong><small>Placed {date(order.createdAt)}</small></div><span className={`status status-${order.status.toLowerCase()}`}>{order.status.replaceAll('_', ' ')}</span></div><div className="order-items">{order.items.map((item) => <span key={`${order.id}-${item.name}`}>{item.quantity}× {item.name}{order.status === 'DELIVERED' && <button onClick={() => window.dispatchEvent(new CustomEvent('techora-review-product', { detail: item.name }))}>Review</button>}</span>)}</div><div className="tracking" aria-label={`Order status: ${order.status}`}>{steps.map((step, index) => <div className={index <= active ? 'complete' : ''} key={step.key}><i>{index < active ? '✓' : index + 1}</i><span>{step.label}</span></div>)}</div><p className="order-total">Total <strong>{money(order.total)}</strong></p></article>; })}</Modal>;
}

export function ProfileModal({ user, close, openOrders, signOut }) {
  const address = user.shippingAddress;
  const [editing, setEditing] = useState(false); const [values, setValues] = useState({ firstName: user.firstName || '', lastName: user.lastName || '', email: user.email || '', phone: user.phone || '', address1: address?.address1 || '', address2: address?.address2 || '', city: address?.city || '', state: address?.state || '', postalCode: address?.postalCode || '', country: address?.country || 'Philippines' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const change = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch('/api/account/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, ...values }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); localStorage.setItem('techora-user', JSON.stringify(data.user)); window.location.reload(); } catch (reason) { setError(reason.message || 'Could not save your profile.'); setSaving(false); } }
  return <Modal close={close} className={`profile-modal ${editing ? 'profile-editing' : ''}`}><p className="eyebrow">Your Techora account</p><h2 id="profile-heading">{editing ? 'Edit profile' : 'Profile'}</h2>{editing ? <form className="auth-form profile-form" onSubmit={save}><div className="two-fields"><Field label="First name" value={values.firstName} onChange={(value) => change('firstName', value)} required /><Field label="Last name" value={values.lastName} onChange={(value) => change('lastName', value)} required /></div><div className="two-fields"><Field label="Email address" type="email" value={values.email} onChange={(value) => change('email', value)} required /><Field label="Mobile number" type="tel" value={values.phone} onChange={(value) => change('phone', value)} required /></div><p className="address-label">Default shipping address</p><Field label="Address line 1" value={values.address1} onChange={(value) => change('address1', value)} required /><Field label="Address line 2" value={values.address2} onChange={(value) => change('address2', value)} /><div className="three-fields"><Field label="City" value={values.city} onChange={(value) => change('city', value)} required /><Field label="Province / State" value={values.state} onChange={(value) => change('state', value)} required /><Field label="Postal code" value={values.postalCode} onChange={(value) => change('postalCode', value)} required /></div><Field label="Country" value={values.country} onChange={(value) => change('country', value)} required />{error && <p className="form-error" role="alert">{error}</p>}<div className="profile-actions"><button type="button" className="profile-signout" onClick={() => setEditing(false)}>Cancel</button><button className="button dark" disabled={saving}>{saving ? 'Saving…' : 'Save changes →'}</button></div></form> : <><div className="profile-avatar">{user.firstName?.[0]}{user.lastName?.[0]}</div><h3>{user.firstName} {user.lastName}</h3><p className="profile-email">{user.email}</p><div className="profile-details"><p><span>Mobile</span><strong>{user.phone || 'Not provided'}</strong></p><p><span>Default shipping address</span><strong>{address ? <>{address.address1}{address.address2 && `, ${address.address2}`}<br />{address.city}, {address.state} {address.postalCode}<br />{address.country}</> : 'Not provided'}</strong></p></div><div className="profile-actions"><button className="button dark" onClick={() => setEditing(true)}>Edit details</button><button className="button dark" onClick={() => { close(); openOrders(); }}>Track orders →</button><button className="profile-signout" onClick={signOut}>Sign out</button></div></>}</Modal>;
}
