import { useEffect, useMemo, useState } from 'react';

const categories = ['All', 'Smartphones', 'Laptops', 'Audio', 'Wearables', 'Tablets', 'Home office', 'Accessories'];
const money = (value) => new Intl.NumberFormat('en-PH', { style: 'currency', currency: 'PHP', maximumFractionDigits: 0 }).format(value);
const emptyRegistration = { firstName: '', lastName: '', email: '', phone: '', password: '', confirmPassword: '', address1: '', address2: '', city: '', state: '', postalCode: '', country: 'Philippines', marketing: false };

function Field({ label, type = 'text', value, onChange, ...props }) {
  const [visible, setVisible] = useState(false); const password = type === 'password';
  return <label className="field"><span>{label}</span><div className={password ? 'password-control' : ''}><input type={password && visible ? 'text' : type} value={value} onChange={(event) => onChange(event.target.value)} {...props} />{password && <button type="button" onClick={() => setVisible(!visible)} aria-label={visible ? 'Hide password' : 'Show password'} title={visible ? 'Hide password' : 'Show password'}>{visible ? 'Hide' : 'Show'}</button>}</div></label>;
}

function AuthModal({ mode, close, success, switchMode }) {
  const signingUp = mode === 'signup'; const forgot = mode === 'forgot';
  const [login, setLogin] = useState({ email: localStorage.getItem('techora-remembered-email') || '', password: '' });
  const [registration, setRegistration] = useState(emptyRegistration);
  const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const [saving, setSaving] = useState(false); const [remember, setRemember] = useState(Boolean(localStorage.getItem('techora-remembered-email')));
  const update = (name, value) => signingUp ? setRegistration((values) => ({ ...values, [name]: value })) : setLogin((values) => ({ ...values, [name]: value }));
  async function submit(event) {
    event.preventDefault(); setError('');
    if (forgot) { setSaving(true); try { const response = await fetch('/api/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: login.email }) }); const result = await response.json(); if (!response.ok) throw new Error(result.message); setError(''); setMessage(result.message); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } return; }
    if (signingUp && registration.password !== registration.confirmPassword) return setError('Passwords do not match.');
    setSaving(true);
    try {
      const response = await fetch(signingUp ? '/api/auth/register' : '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(signingUp ? registration : login) });
      const raw = await response.text();
      let result;
      try { result = JSON.parse(raw); }
      catch { throw new Error(`The server returned an invalid response (${response.status}). Restart the backend and try again.`); }
      if (!response.ok) throw new Error(result.message || 'Something went wrong.');
      if (!signingUp) { if (remember) localStorage.setItem('techora-remembered-email', login.email); else localStorage.removeItem('techora-remembered-email'); } localStorage.setItem('techora-user', JSON.stringify(result.user)); success(result.user); close();
    } catch (requestError) { setError(requestError.message); } finally { setSaving(false); }
  }
  return <div className="modal-layer" onMouseDown={close}><section className={`auth-modal ${signingUp ? 'wide' : ''}`} role="dialog" aria-modal="true" aria-labelledby="account-heading" onMouseDown={(event) => event.stopPropagation()}>
    <button className="modal-close" aria-label="Close account form" onClick={close}>×</button><p className="eyebrow">{signingUp ? 'Create your account' : forgot ? 'Account recovery' : 'Welcome back'}</p>
    <h2 id="account-heading">{signingUp ? 'Shop smarter, from the start.' : forgot ? 'Reset your password.' : 'Good to see you.'}</h2><p className="modal-copy">{signingUp ? 'Save your delivery details, track orders, and check out faster.' : forgot ? 'Enter your email and we’ll prepare password reset instructions.' : 'Sign in to your Techora account.'}</p>
    <form className="auth-form" onSubmit={submit}>
      {signingUp && <><div className="two-fields"><Field label="First name" value={registration.firstName} onChange={(value) => update('firstName', value)} required /><Field label="Last name" value={registration.lastName} onChange={(value) => update('lastName', value)} required /></div><div className="two-fields"><Field label="Email address" type="email" value={registration.email} onChange={(value) => update('email', value)} required /><Field label="Mobile number" type="tel" value={registration.phone} onChange={(value) => update('phone', value)} required /></div><p className="address-label">Default shipping address</p><Field label="Address line 1" value={registration.address1} onChange={(value) => update('address1', value)} required /><Field label="Address line 2 (unit, building, etc.)" value={registration.address2} onChange={(value) => update('address2', value)} /><div className="three-fields"><Field label="City / Municipality" value={registration.city} onChange={(value) => update('city', value)} required /><Field label="Province / State" value={registration.state} onChange={(value) => update('state', value)} required /><Field label="Postal code" value={registration.postalCode} onChange={(value) => update('postalCode', value)} required /></div><Field label="Country" value={registration.country} onChange={(value) => update('country', value)} required /></>}
      {!signingUp && <Field label="Email address" type="email" value={login.email} onChange={(value) => update('email', value)} required />}
      {!forgot && <Field label="Password" type="password" minLength="8" value={signingUp ? registration.password : login.password} onChange={(value) => update('password', value)} required />}{!signingUp && !forgot && <label className="checkbox"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> Remember Me</label>}
      {signingUp && <><Field label="Confirm password" type="password" minLength="8" value={registration.confirmPassword} onChange={(value) => update('confirmPassword', value)} required /><label className="checkbox"><input type="checkbox" checked={registration.marketing} onChange={(event) => update('marketing', event.target.checked)} /> Send me new products and exclusive offers.</label></>}
      {error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success">{message}</p>}<button className="button dark" disabled={saving}>{saving ? 'Please wait…' : signingUp ? 'Create account →' : forgot ? 'Send instructions →' : 'Sign in'}</button>
    </form>{!signingUp && !forgot && <button className="forgot-link" onClick={() => switchMode('forgot')}>Forgot password?</button>}<p className="switcher">{signingUp ? 'Already have an account?' : 'New to Techora?'} <button onClick={() => switchMode(signingUp ? 'login' : 'signup')}>{signingUp ? 'Sign in' : 'Create an account'}</button></p>
  </section></div>;
}

function OrdersModal({ user, close }) {
  const [orders, setOrders] = useState([]); const [error, setError] = useState('');
  useEffect(() => { fetch(`/api/orders?userId=${encodeURIComponent(user.id)}`).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message); return data; }).then(setOrders).catch((reason) => setError(reason.message || 'Could not load your orders.')); }, [user.id]);
  const steps = [{ key: 'PENDING', label: 'Order placed' }, { key: 'CONFIRMED', label: 'Confirmed' }, { key: 'PROCESSING', label: 'Processing' }, { key: 'SHIPPED', label: 'Shipped' }, { key: 'OUT_FOR_DELIVERY', label: 'Out for delivery' }, { key: 'DELIVERED', label: 'Delivered' }];
  const statusIndex = (status) => steps.findIndex((step) => step.key === status);
  const date = (value) => new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(value));
  return <div className="modal-layer" onMouseDown={close}><section className="orders-modal" role="dialog" aria-modal="true" aria-labelledby="orders-heading" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close order tracking">×</button><p className="eyebrow">Your Techora account</p><h2 id="orders-heading">Order tracking</h2><p className="modal-copy">Track every order from confirmation to delivery.</p>{error && <p className="form-error">{error}</p>}{!error && !orders.length && <p className="empty">You have not placed an order yet.</p>}{orders.map((order) => { const active = statusIndex(order.status); return <article className="order-card" key={order.id}><div className="order-head"><div><strong>{order.id}</strong><small>Placed {date(order.createdAt)}</small></div><span className={`status status-${order.status.toLowerCase()}`}>{order.status.replaceAll('_', ' ')}</span></div><div className="order-items">{order.items.map((item) => <span key={`${order.id}-${item.name}`}>{item.quantity}× {item.name}{order.status === 'DELIVERED' && <button onClick={() => window.dispatchEvent(new CustomEvent('techora-review-product', { detail: item.name }))}>Review</button>}</span>)}</div><div className="tracking" aria-label={`Order status: ${order.status}`}>{steps.map((step, index) => <div className={index <= active ? 'complete' : ''} key={step.key}><i>{index < active ? '✓' : index + 1}</i><span>{step.label}</span></div>)}</div><p className="order-total">Total <strong>{money(order.total)}</strong></p></article>; })}</section></div>;
}

function ProfileModal({ user, close, openOrders, signOut }) {
  const address = user.shippingAddress;
  const [editing, setEditing] = useState(false); const [values, setValues] = useState({ firstName: user.firstName || '', lastName: user.lastName || '', email: user.email || '', phone: user.phone || '', address1: address?.address1 || '', address2: address?.address2 || '', city: address?.city || '', state: address?.state || '', postalCode: address?.postalCode || '', country: address?.country || 'Philippines' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const change = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch('/api/account/profile', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, ...values }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); localStorage.setItem('techora-user', JSON.stringify(data.user)); window.location.reload(); } catch (reason) { setError(reason.message || 'Could not save your profile.'); setSaving(false); } }
  return <div className="modal-layer" onMouseDown={close}><section className={`profile-modal ${editing ? 'profile-editing' : ''}`} role="dialog" aria-modal="true" aria-labelledby="profile-heading" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close profile">×</button><p className="eyebrow">Your Techora account</p><h2 id="profile-heading">{editing ? 'Edit profile' : 'Profile'}</h2>{editing ? <form className="auth-form profile-form" onSubmit={save}><div className="two-fields"><Field label="First name" value={values.firstName} onChange={(value) => change('firstName', value)} required /><Field label="Last name" value={values.lastName} onChange={(value) => change('lastName', value)} required /></div><div className="two-fields"><Field label="Email address" type="email" value={values.email} onChange={(value) => change('email', value)} required /><Field label="Mobile number" type="tel" value={values.phone} onChange={(value) => change('phone', value)} required /></div><p className="address-label">Default shipping address</p><Field label="Address line 1" value={values.address1} onChange={(value) => change('address1', value)} required /><Field label="Address line 2" value={values.address2} onChange={(value) => change('address2', value)} /><div className="three-fields"><Field label="City" value={values.city} onChange={(value) => change('city', value)} required /><Field label="Province / State" value={values.state} onChange={(value) => change('state', value)} required /><Field label="Postal code" value={values.postalCode} onChange={(value) => change('postalCode', value)} required /></div><Field label="Country" value={values.country} onChange={(value) => change('country', value)} required />{error && <p className="form-error">{error}</p>}<div className="profile-actions"><button type="button" className="profile-signout" onClick={() => setEditing(false)}>Cancel</button><button className="button dark" disabled={saving}>{saving ? 'Saving…' : 'Save changes →'}</button></div></form> : <><div className="profile-avatar">{user.firstName?.[0]}{user.lastName?.[0]}</div><h3>{user.firstName} {user.lastName}</h3><p className="profile-email">{user.email}</p><div className="profile-details"><p><span>Mobile</span><strong>{user.phone || 'Not provided'}</strong></p><p><span>Default shipping address</span><strong>{address ? <>{address.address1}{address.address2 && `, ${address.address2}`}<br />{address.city}, {address.state} {address.postalCode}<br />{address.country}</> : 'Not provided'}</strong></p></div><div className="profile-actions"><button className="button dark" onClick={() => setEditing(true)}>Edit details</button><button className="button dark" onClick={() => { close(); openOrders(); }}>Track orders →</button><button className="profile-signout" onClick={signOut}>Sign out</button></div></>}</section></div>;
}

function ProductModal({ product, close, add, user }) {
  const account = user || JSON.parse(localStorage.getItem('techora-user') || 'null'); const [reviews, setReviews] = useState([]); const [rating, setRating] = useState(5); const [comment, setComment] = useState(''); const [reviewMessage, setReviewMessage] = useState(''); const [sending, setSending] = useState(false);
  const loadReviews = () => fetch(`/api/products/${product.id}/reviews`).then((response) => response.json()).then(setReviews).catch(() => setReviews([]));
  useEffect(() => { loadReviews(); }, [product.id]);
  async function submitReview(event) { event.preventDefault(); if (!account) return setReviewMessage('Sign in to leave a review.'); setSending(true); try { const response = await fetch(`/api/products/${product.id}/reviews`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: account.id, rating, comment }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setComment(''); setReviewMessage(data.message); loadReviews(); } catch (error) { setReviewMessage(error.message); } finally { setSending(false); } }
  const stockText = product.stock === 0 ? 'Out of stock' : product.stock <= 5 ? `Only ${product.stock} left in stock` : `In stock · ${product.stock} available`;
  return <div className="modal-layer" onMouseDown={close}><section className="product-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close product details">×</button><div className="product-detail-image"><img src={product.image} alt={product.name} /></div><div className="product-detail-copy"><p className="eyebrow">{product.category}</p><h2>{product.name}</h2><p className="detail-price">{money(product.price)}</p><p className="rating">★ {product.rating} <span>({product.reviews} ratings)</span></p><p className={`stock-status ${product.stock === 0 ? 'out' : product.stock <= 5 ? 'low' : ''}`}>{stockText}</p><p className="description">{product.description}</p><button className="button dark" disabled={product.stock === 0} onClick={() => { add(product); close(); }}>{product.stock === 0 ? 'Out of stock' : 'Add to bag →'}</button><div className="review-section"><h3>Customer reviews</h3>{reviews.length ? reviews.map((review) => <article key={review.id}><strong>{review.customer}</strong><span>{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</span><p>{review.comment}</p></article>) : <p className="empty">No reviews yet. Delivered customers can be the first to share feedback.</p>}<form className="review-form" onSubmit={submitReview}><label>Rate this product<select value={rating} onChange={(event) => setRating(Number(event.target.value))}>{[5, 4, 3, 2, 1].map((value) => <option value={value} key={value}>{value} star{value > 1 ? 's' : ''}</option>)}</select></label><textarea value={comment} onChange={(event) => setComment(event.target.value)} minLength="3" placeholder="Share your experience after delivery" required /><button className="review-submit" disabled={sending}>{sending ? 'Sending…' : 'Submit review'}</button>{reviewMessage && <p className="review-message">{reviewMessage}</p>}</form></div></div></section></div>;
}

function AdminPanel({ user, close }) {
  const modules = [{ id: 'Dashboard', label: 'Dashboard', icon: 'dashboard' }, { id: 'Product', label: 'Products', icon: 'products' }, { id: 'Order', label: 'Orders', icon: 'orders' }, { id: 'Customers', label: 'Customers', icon: 'customers' }, { id: 'Promotions & reviews', label: 'Promotions & reviews', icon: 'promotions' }, { id: 'Reports & settings', label: 'Reports & settings', icon: 'reports' }];
  const savedSection = localStorage.getItem(`techora-admin-section-${user.id}`); const [section, setSection] = useState(modules.some((item) => item.id === savedSection) ? savedSection : 'Dashboard'); const [dashboard, setDashboard] = useState(null); const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); const [customers, setCustomers] = useState([]); const [promotions, setPromotions] = useState([]); const [reports, setReports] = useState(null); const [message, setMessage] = useState(''); const [editorProduct, setEditorProduct] = useState(undefined); const [deletingProduct, setDeletingProduct] = useState(null); const [adminMenu, setAdminMenu] = useState(false); const [insightModal, setInsightModal] = useState(null); const [productCategory, setProductCategory] = useState('All');
  const load = async () => { try { const [summary, productRows, orderRows, customerRows, promotionRows, reportData] = await Promise.all(['dashboard', 'products', 'orders', 'customers', 'promotions-reviews', 'reports-settings'].map(async (path) => { const response = await fetch(`/api/admin/${path}?userId=${user.id}`); const data = await response.json(); if (!response.ok) throw new Error(data.message); return data; })); setDashboard(summary); setProducts(productRows); setOrders(orderRows); setCustomers(customerRows); setPromotions(promotionRows); setReports(reportData); } catch (error) { setMessage(error.message); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { document.body.classList.add('admin-open'); return () => document.body.classList.remove('admin-open'); }, []);
  useEffect(() => { localStorage.setItem(`techora-admin-section-${user.id}`, section); }, [section, user.id]);
  async function updateProduct(id, patch) { const response = await fetch(`/api/admin/products/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, ...patch }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message); setProducts((items) => items.map((item) => item.id === id ? data.product : item)); window.dispatchEvent(new CustomEvent('techora-catalog-changed')); setMessage('Product saved.'); }
  async function saveEditor(form) { const editing = Boolean(form.id); const response = await fetch(editing ? `/api/admin/products/${form.id}` : '/api/admin/products', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, ...form }) }); const data = await response.json(); if (!response.ok) return data.message || 'Could not save product.'; setProducts((items) => editing ? items.map((item) => item.id === form.id ? data.product : item) : [data.product, ...items]); window.dispatchEvent(new CustomEvent('techora-catalog-changed')); setMessage(editing ? 'Product updated.' : 'Product added.'); return null; }
  async function deleteProduct(product, password) { const response = await fetch(`/api/admin/products/${product.id}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, password }) }); const data = await response.json(); if (!response.ok) return data.message || 'Could not delete product.'; setProducts((items) => items.filter((item) => item.id !== product.id)); window.dispatchEvent(new CustomEvent('techora-catalog-changed', { detail: { deletedId: product.id } })); setMessage(data.message); return null; }
  async function updateStatus(id, status) { const response = await fetch(`/api/admin/orders/${id}/status`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, status }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message); setOrders((items) => items.map((item) => item.id === id ? { ...item, status } : item)); setMessage('Order status updated.'); }
  const stockRows = products.filter((product) => product.stock <= 5); const productCategories = ['All', ...new Set(products.map((product) => product.category).filter(Boolean))]; const visibleProducts = productCategory === 'All' ? products : products.filter((product) => product.category === productCategory);
  const content = () => {
    if (section === 'Dashboard') return <><div className="admin-heading"><div><p className="eyebrow">Platform overview</p><h2>Good morning, Admin.</h2></div><button className="button dark" onClick={load}>Refresh data</button></div><div className="metric-grid"><Metric label="Revenue" value={dashboard ? money(dashboard.revenue) : '—'} /><Metric label="Orders" value={dashboard?.orders ?? '—'} /><Metric label="Customers" value={dashboard?.customers ?? '—'} /><Metric label="Low stock alerts" value={dashboard?.lowStock?.length ?? '—'} /></div><DashboardInsights dashboard={dashboard} open={setInsightModal} /><section className="admin-card"><h3>Low-stock alerts</h3>{dashboard?.lowStock?.length ? dashboard.lowStock.map((product) => <p className="alert-row" key={product.id}><span>{product.name}</span><strong>{product.stock} left</strong></p>) : <p className="empty">All products have healthy stock levels.</p>}</section></>;
    if (section === 'Product') return <><div className="admin-heading"><div><p className="eyebrow">Catalog management</p><h2>Products & pricing</h2></div><button className="button dark" onClick={() => setEditorProduct(null)}>Add product</button></div><div className="admin-product-controls"><label>Category <select value={productCategory} onChange={(event) => setProductCategory(event.target.value)}>{productCategories.map((item) => <option key={item}>{item}</option>)}</select></label></div><section className="admin-card admin-table"><div className="table-head"><span>Product</span><span>Category</span><span>Price (₱)</span><span>Stock</span><span>Actions</span></div>{visibleProducts.length ? visibleProducts.map((product) => <ProductRow key={product.id} product={product} onSave={updateProduct} onEdit={setEditorProduct} onDelete={setDeletingProduct} />) : <p className="empty admin-filter-empty">No products found in this category.</p>}</section></>;
    if (section === 'Order') return <><div className="admin-heading"><div><p className="eyebrow">Fulfilment</p><h2>Orders & delivery</h2></div></div><section className="admin-card admin-table"><div className="order-table-head"><span>Order</span><span>Customer</span><span>Total</span><span>Status</span></div>{orders.length ? orders.map((order) => <div className="order-table-row" key={order.id}><strong>{order.id}</strong><span>{order.customer}</span><span>{money(order.total)}</span><select value={order.status} onChange={(event) => updateStatus(order.id, event.target.value)}>{['PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED'].map((status) => <option key={status}>{status}</option>)}</select></div>) : <p className="empty">No orders yet.</p>}</section></>;
    if (section === 'Customers') return <><div className="admin-heading"><div><p className="eyebrow">Customer management</p><h2>Customers</h2></div></div><section className="admin-card admin-table"><div className="customer-table-head"><span>Customer</span><span>Contact</span><span>Location</span><span>Orders</span><span>Total spend</span></div>{customers.length ? customers.map((customer) => <div className="customer-table-row" key={customer.id}><strong>{customer.name}</strong><span>{customer.email}<small>{customer.phone}</small></span><span>{customer.city ? `${customer.city}, ${customer.state}` : 'No address yet'}</span><span>{customer.orderCount}</span><strong>{money(customer.orderTotal)}</strong></div>) : <p className="empty">No customer accounts yet.</p>}</section></>;
    if (section === 'Promotions & reviews') return <><div className="admin-heading"><div><p className="eyebrow">Growth & feedback</p><h2>Promotions & reviews</h2></div></div><div className="metric-grid"><Metric label="Featured products" value={promotions.filter((product) => product.badge).length} /><Metric label="Catalog reviews" value={promotions.reduce((sum, product) => sum + product.reviews, 0)} /><Metric label="Average rating" value={promotions.length ? (promotions.reduce((sum, product) => sum + Number(product.rating), 0) / promotions.length).toFixed(1) : '—'} /><Metric label="Active badges" value={promotions.filter((product) => product.badge).length} /></div><section className="admin-card admin-table"><div className="promotion-table-head"><span>Product</span><span>Promotion</span><span>Rating</span><span>Reviews</span><span>Price</span></div>{promotions.map((product) => <div className="promotion-table-row" key={product.id}><strong>{product.name}</strong><span>{product.badge || 'No active promotion'}</span><span>★ {product.rating}</span><span>{product.reviews}</span><strong>{money(product.price)}</strong></div>)}</section></>;
    return <><div className="admin-heading"><div><p className="eyebrow">Platform controls</p><h2>Reports & settings</h2></div></div><div className="metric-grid"><Metric label="Products" value={reports?.inventory?.products ?? '—'} /><Metric label="Units in stock" value={reports?.inventory?.units ?? '—'} /><Metric label="Low stock" value={reports?.inventory?.low_stock ?? '—'} /><Metric label="Currency" value={reports?.currency ?? 'PHP'} /></div><div className="report-grid"><section className="admin-card"><h3>User accounts & roles</h3>{reports?.roles?.map((role) => <p className="alert-row" key={role.role}><span>{role.role}</span><strong>{role.count} users</strong></p>)}</section><section className="admin-card"><h3>System settings</h3><p className="setting-row"><span>Store</span><strong>{reports?.store ?? 'Techora'}</strong></p><p className="setting-row"><span>Currency</span><strong>Philippine peso (PHP)</strong></p><p className="setting-row"><span>Audit log</span><strong>Order status updates enabled</strong></p></section></div></>;
  };
  return <><div className="admin-shell" role="dialog" aria-modal="true"><aside className={`admin-sidebar ${adminMenu ? 'menu-open' : ''}`}><div className="admin-brand"><button className="admin-menu-toggle" aria-label="Open admin menu" aria-expanded={adminMenu} onClick={() => setAdminMenu((open) => !open)}><i /><i /><i /></button><button className="logo" onClick={close}>TECH<span>ORA</span></button></div><div className="admin-navigation"><p>Administration</p>{modules.map((item) => <button className={section === item.id ? 'active' : ''} onClick={() => { setSection(item.id); setAdminMenu(false); }} key={item.id}><span className="admin-nav-icon" aria-hidden="true"><AdminNavIcon name={item.icon} /></span>{item.label}</button>)}<div className="admin-user"><span>Signed in as</span><strong>{user.firstName} {user.lastName}</strong><small>{user.email}</small></div><button className="exit-admin" onClick={close}>← Back to storefront</button></div></aside><main className="admin-main">{message && <button className="admin-message" onClick={() => setMessage('')}>{message}</button>}{content()}</main></div>{editorProduct !== undefined && <ProductEditor product={editorProduct} save={saveEditor} close={() => setEditorProduct(undefined)} />}{deletingProduct && <DeleteProductModal product={deletingProduct} remove={deleteProduct} close={() => setDeletingProduct(null)} />}{insightModal && <DashboardInsightModal type={insightModal} dashboard={dashboard} close={() => setInsightModal(null)} />}</>;
}

function AdminNavIcon({ name }) {
  const shared = { viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: '1.8', strokeLinecap: 'round', strokeLinejoin: 'round' };
  if (name === 'dashboard') return <svg {...shared}><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></svg>;
  if (name === 'products') return <svg {...shared}><path d="m4 8 8-4 8 4-8 4-8-4Z" /><path d="M4 8v8l8 4 8-4V8M12 12v8" /></svg>;
  if (name === 'orders') return <svg {...shared}><path d="M7 3h10v18H7z" /><path d="M9 3v4h6V3M10 12h4M10 16h4" /></svg>;
  if (name === 'customers') return <svg {...shared}><circle cx="9" cy="8" r="3" /><path d="M3 20c.5-4 2.5-6 6-6s5.5 2 6 6M16 5a3 3 0 0 1 0 6M18 14c2 1 3 3 3 5" /></svg>;
  if (name === 'promotions') return <svg {...shared}><path d="M3 12V5h7l10 10-7 7L3 12Z" /><circle cx="8" cy="8" r="1" /></svg>;
  return <svg {...shared}><path d="M4 19V5M12 19V5M20 19V5" /><path d="M2 8h4M10 15h4M18 10h4" /><circle cx="6" cy="8" r="2" /><circle cx="12" cy="15" r="2" /><circle cx="18" cy="10" r="2" /></svg>;
}
function Metric({ label, value }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
function DashboardInsights({ dashboard, open }) {
  const popular = dashboard?.popularProducts || []; const topOrders = dashboard?.topOrders || []; const topCustomers = dashboard?.topCustomers || [];
  return <div className="dashboard-insights">
    <button className="admin-card insight-card insight-open" onClick={() => open('products')}><div className="insight-heading"><div><p className="eyebrow">Best sellers</p><h3>Popular products</h3></div><span>Top 5 · View</span></div>{popular.length ? popular.map((product, index) => <div className="popular-product" key={product.id}><b>{index + 1}</b><img src={product.image} alt="" /><div><strong>{product.name}</strong><small>{product.category}</small></div><span>{product.unitsSold} sold</span></div>) : <p className="empty">Sales will appear here after orders are placed.</p>}</button>
    <button className="admin-card insight-card insight-open" onClick={() => open('orders')}><div className="insight-heading"><div><p className="eyebrow">Highest value</p><h3>Top purchase orders</h3></div><span>Top 5 · View</span></div>{topOrders.length ? topOrders.map((order) => <div className="insight-row" key={order.id}><div><strong>{order.id}</strong><small>{order.customer} · {order.itemCount} item{order.itemCount === 1 ? '' : 's'}</small></div><b>{money(order.total)}</b></div>) : <p className="empty">No completed purchases yet.</p>}</button>
    <button className="admin-card insight-card insight-open" onClick={() => open('customers')}><div className="insight-heading"><div><p className="eyebrow">Returning shoppers</p><h3>Top customers</h3></div><span>Top 5 · View</span></div>{topCustomers.length ? topCustomers.map((customer) => <div className="insight-row" key={customer.id}><div><strong>{customer.name}</strong><small>{customer.orderCount} order{customer.orderCount === 1 ? '' : 's'} · {customer.email}</small></div><b>{money(customer.totalSpent)}</b></div>) : <p className="empty">Customer activity will appear here.</p>}</button>
  </div>;
}
function DashboardInsightModal({ type, dashboard, close }) {
  const labels = { products: ['Best sellers', 'Popular products'], orders: ['Highest-value purchases', 'Top purchase orders'], customers: ['Returning shoppers', 'Top customers'] }; const [eyebrow, title] = labels[type];
  const rows = type === 'products' ? dashboard?.popularProducts || [] : type === 'orders' ? dashboard?.topOrders || [] : dashboard?.topCustomers || [];
  return <div className="modal-layer" onMouseDown={close}><section className="insight-modal" role="dialog" aria-modal="true" aria-labelledby="insight-modal-title" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close dashboard details">×</button><p className="eyebrow">{eyebrow}</p><h2 id="insight-modal-title">{title}</h2><p className="modal-copy">Showing the five strongest results from your current store data.</p><div className="insight-modal-list">{rows.length ? rows.map((row, index) => type === 'products' ? <article className="insight-detail-product" key={row.id}><b>{index + 1}</b><img src={row.image} alt="" /><div><strong>{row.name}</strong><small>{row.category} · {money(row.price)}</small></div><span><strong>{row.unitsSold}</strong> units sold<br />{row.orderCount} order{row.orderCount === 1 ? '' : 's'}</span></article> : type === 'orders' ? <article className="insight-detail-row" key={row.id}><div><strong>{row.id}</strong><small>{row.customer} · {row.itemCount} item{row.itemCount === 1 ? '' : 's'} · {row.status.replaceAll('_', ' ')}</small></div><b>{money(row.total)}</b></article> : <article className="insight-detail-row" key={row.id}><div><strong>{row.name}</strong><small>{row.email} · {row.orderCount} order{row.orderCount === 1 ? '' : 's'}</small></div><b>{money(row.totalSpent)}</b></article>) : <p className="empty">There is no data to show yet.</p>}</div></section></div>;
}
function ProductEditor({ product, save, close }) {
  const adding = !product; const [form, setForm] = useState(product || { name: '', category: 'Smartphones', price: '', stock: 10, image: '', imageData: '', description: '' }); const [error, setError] = useState('');
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  function uploadImage(event) { const file = event.target.files?.[0]; if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp', 'image/gif'].includes(file.type)) return setError('Please choose a JPG, PNG, WebP, or GIF image.'); if (file.size > 4 * 1024 * 1024) return setError('Image must be smaller than 4 MB.'); const reader = new FileReader(); reader.onload = () => { update('imageData', reader.result); update('image', ''); setError(''); }; reader.readAsDataURL(file); }
  async function submit(event) { event.preventDefault(); const result = await save({ ...form, price: Number(form.price), stock: Number(form.stock) }); if (result) setError(result); else close(); }
  return <div className="modal-layer" onMouseDown={close}><section className="product-editor" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close product editor">×</button><p className="eyebrow">Admin catalog</p><h2>{adding ? 'Add product' : 'Edit product'}</h2><form className="auth-form" onSubmit={submit}><Field label="Product name" value={form.name} onChange={(value) => update('name', value)} required /><label className="field"><span>Category</span><select value={form.category} onChange={(event) => update('category', event.target.value)}>{categories.filter((item) => item !== 'All').map((item) => <option key={item}>{item}</option>)}</select></label><div className="two-fields"><Field label="Price (₱)" type="number" value={form.price} onChange={(value) => update('price', value)} required /><Field label="Stock quantity" type="number" value={form.stock} onChange={(value) => update('stock', value)} required /></div><label className="field image-upload"><span>Product image</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadImage} required={adding && !form.image} /><small>JPG, PNG, WebP, or GIF · maximum 4 MB</small></label>{(form.imageData || form.image) && <img className="upload-preview" src={form.imageData || form.image} alt="Product upload preview" />}<label className="field"><span>Description</span><textarea value={form.description || ''} onChange={(event) => update('description', event.target.value)} placeholder="Product description" /></label>{error && <p className="form-error">{error}</p>}<button className="button dark">{adding ? 'Add product →' : 'Save product →'}</button></form></section></div>;
}
function DeleteProductModal({ product, remove, close }) {
  const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event) { event.preventDefault(); setSaving(true); const result = await remove(product, password); setSaving(false); if (result) setError(result); else close(); }
  return <div className="modal-layer" onMouseDown={close}><section className="delete-product-modal" role="dialog" aria-modal="true" aria-labelledby="delete-product-title" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close delete confirmation">×</button><p className="eyebrow">Permanent action</p><h2 id="delete-product-title">Delete {product.name}?</h2><p>This permanently removes the product, its reviews, and its uploaded image. It cannot be undone.</p><form className="auth-form" onSubmit={submit}><Field label="Admin password" type="password" value={password} onChange={setPassword} autoComplete="current-password" required />{error && <p className="form-error">{error}</p>}<div className="delete-actions"><button type="button" onClick={close}>Cancel</button><button className="delete-product-button" disabled={saving}>{saving ? 'Deleting…' : 'Permanently delete'}</button></div></form></section></div>;
}
function ProductRow({ product, onSave, onEdit, onDelete }) { const [price, setPrice] = useState(product.price); const [stock, setStock] = useState(product.stock); useEffect(() => { setPrice(product.price); setStock(product.stock); }, [product]); return <div className={`product-row ${product.stock <= 5 ? 'low' : ''}`}><strong className="admin-product-name"><img src={product.image} alt="" />{product.name}</strong><span>{product.category}</span><label className="admin-edit-field"><small>Price (₱)</small><input type="number" min="0" value={price} onChange={(event) => setPrice(event.target.value)} /></label><label className="admin-edit-field"><small>Stock</small><input type="number" min="0" value={stock} onChange={(event) => setStock(event.target.value)} /></label><div className="row-actions"><button onClick={() => onSave(product.id, { price: Number(price), stock: Number(stock) })}>Save</button><button className="edit-product" onClick={() => onEdit(product)}>Edit</button><button className="delete-row-button" onClick={() => onDelete(product)}>Delete</button></div></div>; }

export default function App() {
  const [products, setProducts] = useState([]); const [category, setCategory] = useState('All'); const [sort, setSort] = useState(''); const [catalogVersion, setCatalogVersion] = useState(0);
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('techora-cart-php') || '[]')); const [drawer, setDrawer] = useState(false); const [checkout, setCheckout] = useState(false); const [auth, setAuth] = useState(null); const [ordersOpen, setOrdersOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [productView, setProductView] = useState(null); const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('techora-user') || 'null')); const [notice, setNotice] = useState(''); const [placingOrder, setPlacingOrder] = useState(false); const [mobileMenu, setMobileMenu] = useState(false);
  const cartCount = useMemo(() => cart.reduce((count, item) => count + item.quantity, 0), [cart]); const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  useEffect(() => { const query = new URLSearchParams(); if (category !== 'All') query.set('category', category); if (sort) query.set('sort', sort); fetch(`/api/products?${query}`).then((res) => res.json()).then(setProducts).catch(() => setNotice('Unable to load products. Please refresh.')); }, [category, sort, catalogVersion]);
  useEffect(() => { const syncCatalog = (event) => { if (event.detail?.deletedId) setCart((items) => items.filter((item) => item.id !== event.detail.deletedId)); setCatalogVersion((version) => version + 1); }; window.addEventListener('techora-catalog-changed', syncCatalog); return () => window.removeEventListener('techora-catalog-changed', syncCatalog); }, []);
  useEffect(() => localStorage.setItem('techora-cart-php', JSON.stringify(cart)), [cart]);
  useEffect(() => { const openReview = (event) => { const product = products.find((item) => item.name === event.detail); if (product) { setOrdersOpen(false); setProductView(product); } }; window.addEventListener('techora-review-product', openReview); return () => window.removeEventListener('techora-review-product', openReview); }, [products]);
  useEffect(() => {
    const actions = document.querySelector('.actions'); const accountButton = actions?.querySelector('.round');
    if (!actions || !accountButton) return undefined;
    if (!user) { accountButton.textContent = 'Sign in'; accountButton.setAttribute('title', 'Sign in'); return () => { accountButton.textContent = '◉'; }; }
    accountButton.style.display = 'none';
    const links = document.createElement('div'); links.className = 'customer-text-links';
    [['Profile', () => setProfileOpen(true)], ['Orders', () => setOrdersOpen(true)]].forEach(([label, action]) => { const button = document.createElement('button'); button.textContent = label; button.addEventListener('click', action); links.appendChild(button); });
    actions.insertBefore(links, accountButton);
    return () => { accountButton.style.display = ''; links.remove(); };
  }, [user]);
  useEffect(() => { const openProduct = (event) => { const card = event.target.closest('.card'); if (!card || event.target.closest('button')) return; const name = card.querySelector('h3')?.textContent; const product = products.find((item) => item.name === name); if (product) setProductView(product); }; document.addEventListener('click', openProduct); return () => document.removeEventListener('click', openProduct); }, [products]);
  useEffect(() => { if (!drawer) return undefined; const closeOnOutsideClick = (event) => { if (!event.target.closest('.drawer') && !event.target.closest('.bag')) setDrawer(false); }; document.addEventListener('mousedown', closeOnOutsideClick); return () => document.removeEventListener('mousedown', closeOnOutsideClick); }, [drawer]);
  const go = (id) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  function add(product) { if (!user) { setAuth('login'); setNotice('Sign in to add items to your bag.'); return; } if (product.stock === 0) return setNotice(`${product.name} is currently out of stock.`); setCart((items) => { const existing = items.find((item) => item.id === product.id); return existing ? items.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { ...product, quantity: 1 }]; }); setNotice(`${product.name} added to your bag.`); }
  function signOut() { localStorage.removeItem('techora-user'); setUser(null); setProfileOpen(false); setMobileMenu(false); setNotice('You have been signed out.'); }
  function updateQuantity(id, delta) { setCart((items) => items.map((item) => item.id === id ? { ...item, quantity: item.quantity + delta } : item).filter((item) => item.quantity > 0)); }
  function authenticate(account) { if (account.role === 'ADMIN') localStorage.removeItem(`techora-admin-section-${account.id}`); setUser(account); setNotice(`Welcome to Techora, ${account.firstName}.`); }
  async function placeOrder() {
    setPlacingOrder(true);
    try {
      const response = await fetch('/api/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, items: cart.map(({ id, quantity }) => ({ id, quantity })) }) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.message || result.error || 'Could not place your order.');
      setCart([]); setCheckout(false); setNotice(`Order ${result.order.id} confirmed — total ${money(result.order.total)}.`);
    } catch (error) { setNotice(error.message); } finally { setPlacingOrder(false); }
  }
  return <>{user?.role === 'ADMIN' && <AdminPanel user={user} close={() => { localStorage.removeItem('techora-user'); setUser(null); }} />}<div className="announcement">Complimentary shipping on orders over ₱6,250 <span>•</span> 30-day returns</div><header className="site-header"><button className="logo" onClick={() => go('top')}>TECH<span>ORA</span></button><nav><button onClick={() => go('top')}>Home</button><button onClick={() => go('shop')}>Products</button><button onClick={() => go('shop')}>Categories</button><button onClick={() => go('why')}>Why Techora</button></nav><div className="actions"><button className="round" aria-label={user ? 'Open profile' : 'Open account'} title={user ? 'Profile' : 'Account'} onClick={() => user ? setProfileOpen(true) : setAuth('login')}>◉</button>{user && <button className="sign-out" onClick={signOut}>Sign out</button>}<button className="bag" aria-label="Open shopping bag" onClick={() => { setMobileMenu(false); setDrawer(true); }}>Bag {cartCount > 0 && <span>{cartCount}</span>}</button>{user && <div className="mobile-account"><button className="mobile-menu-toggle" aria-label="Open account menu" aria-expanded={mobileMenu} onClick={() => setMobileMenu((open) => !open)}><i /><i /><i /></button>{mobileMenu && <div className="mobile-account-menu"><button onClick={() => { setMobileMenu(false); setProfileOpen(true); }}>Profile</button><button onClick={() => { setMobileMenu(false); setOrdersOpen(true); }}>Orders</button><button className="mobile-sign-out" onClick={signOut}>Sign out</button></div>}</div>}</div></header>
    <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow">Technology, all in one place</p><h1>Upgrade your<br /><em>digital world.</em></h1><p>Discover phones, laptops, gaming gear and more from trusted vendors.</p><button className="button dark" onClick={() => go('shop')}>Shop the collection →</button></div><div className="hero-art"><i className="orb one" /><i className="orb two" /><img src="https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1300&q=90" alt="Modern smartphone on a dark surface" /></div></section><section className="benefits" id="why"><div><b>✦</b><h3>Trusted vendors</h3><p>Quality technology selected with care.</p></div><div><b>◌</b><h3>Secure shopping</h3><p>Your details are handled thoughtfully.</p></div><div><b>↗</b><h3>Wide selection</h3><p>Everything you need in one place.</p></div></section><section className="shop" id="shop"><p className="eyebrow">The edit</p><h2>Find your next favorite.</h2><div className="filters"><div className="tabs">{categories.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><label>Sort <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="">Featured</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="rating">Highest rated</option></select></label></div><div className="products">{products.map((product) => <article className="card" key={product.id}><div className="photo">{product.badge && <span>{product.badge}</span>}<img src={product.image} alt={product.name} /><button onClick={() => add(product)}>Add to bag</button></div><div className="product-meta"><small>{product.category} · ★ {product.rating}</small><h3>{product.name}</h3><strong>{money(product.price)}</strong></div></article>)}</div></section><section className="account-cta"><p className="eyebrow">Make it yours</p><h2>Save your details. Shop in seconds.</h2><p>Create an account to keep your shipping address ready for checkout and stay on top of every order.</p><button className="button lime" onClick={() => setAuth('signup')}>Create your account →</button></section></main><footer><button className="logo" onClick={() => go('top')}>TECH<span>ORA</span></button><p>Technology for a more considered life.</p><small>© 2026 Techora. All rights reserved.</small></footer>
    {drawer && <aside className="drawer"><div className="drawer-head"><h2>Your bag <small>{cartCount}</small></h2><button className="modal-close" onClick={() => setDrawer(false)} aria-label="Close shopping bag">×</button></div>{cart.length ? <>{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt="" /><div><h3>{item.name}</h3><p>{money(item.price)}</p><div className="quantity"><button onClick={() => updateQuantity(item.id, -1)}>−</button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, 1)}>+</button></div></div><button className="remove" onClick={() => setCart((items) => items.filter((product) => product.id !== item.id))}>Remove</button></div>)}<div className="summary"><p>Subtotal <strong>{money(total)}</strong></p><button className="button dark" onClick={() => { setDrawer(false); if (user) setCheckout(true); else setAuth('signup'); }}>{user ? 'Proceed to checkout →' : 'Create account to checkout →'}</button></div></> : <p className="empty">Your bag is waiting for something good.</p>}</aside>}
    {checkout && <div className="modal-layer" onMouseDown={() => setCheckout(false)}><section className="checkout-modal" role="dialog" aria-modal="true" aria-labelledby="checkout-heading" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setCheckout(false)} aria-label="Close checkout">×</button><p className="eyebrow">Secure test checkout</p><h2 id="checkout-heading">Review your order.</h2><div className="checkout-details"><p><strong>Deliver to</strong><br />{user.firstName} {user.lastName}<br />{user.shippingAddress?.address1}<br />{user.shippingAddress?.city}, {user.shippingAddress?.state} {user.shippingAddress?.postalCode}<br />{user.shippingAddress?.country}</p><p><strong>Payment</strong><br />Cash on delivery (test)</p><p className="checkout-total">Order total <strong>{money(total)}</strong></p></div><button className="button dark" onClick={placeOrder} disabled={placingOrder}>{placingOrder ? 'Placing order…' : `Place order · ${money(total)}`}</button></section></div>}
    {auth && <AuthModal mode={auth} close={() => setAuth(null)} success={authenticate} switchMode={setAuth} />}{profileOpen && <ProfileModal user={user} close={() => setProfileOpen(false)} openOrders={() => setOrdersOpen(true)} signOut={signOut} />}{ordersOpen && <OrdersModal user={user} close={() => setOrdersOpen(false)} />}{productView && <ProductModal product={productView} close={() => setProductView(null)} add={add} />}{notice && <button className="toast" onClick={() => setNotice('')}>{notice}</button>}</>;
}
