import { useEffect, useState } from 'react';
import { Modal, LoadingState, ProductImage } from './ui';
import { money, readResponse } from './lib';

export function ProductModal({ product, close, add, user }) {
  const account = user || JSON.parse(localStorage.getItem('techora-user') || 'null'); const [reviews, setReviews] = useState([]); const [rating, setRating] = useState(5); const [comment, setComment] = useState(''); const [reviewMessage, setReviewMessage] = useState(''); const [sending, setSending] = useState(false);
  const [reviewsLoading, setReviewsLoading] = useState(true); const [reviewsError, setReviewsError] = useState('');
  const loadReviews = () => { setReviewsLoading(true); setReviewsError(''); return fetch(`/api/products/${product.id}/reviews`).then(readResponse).then(setReviews).catch(() => setReviewsError('Reviews could not be loaded. Please try again.')).finally(() => setReviewsLoading(false)); };
  useEffect(() => { loadReviews(); }, [product.id]);
  async function submitReview(event) { event.preventDefault(); if (!account) return setReviewMessage('Sign in to leave a review.'); setSending(true); try { const response = await fetch(`/api/products/${product.id}/reviews`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: account.id, rating, comment }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setComment(''); setReviewMessage(data.message); loadReviews(); } catch (error) { setReviewMessage(error.message); } finally { setSending(false); } }
  const stockText = product.stock === 0 ? 'Out of stock' : product.stock <= 5 ? `Only ${product.stock} left in stock` : `In stock · ${product.stock} available`;
  return <Modal close={close} className="product-modal"><div className="product-detail-image"><ProductImage src={product.image} alt={product.name} /></div><div className="product-detail-copy"><p className="eyebrow">{product.category}</p><h2>{product.name}</h2><p className="detail-price">{money(product.price)}</p><p className="rating">★ {product.rating} <span>({product.reviews} ratings)</span></p><p className={`stock-status ${product.stock === 0 ? 'out' : product.stock <= 5 ? 'low' : ''}`}>{stockText}</p><p className="description">{product.description}</p><button className="button dark" disabled={product.stock === 0} onClick={() => { add(product); close(); }}>{product.stock === 0 ? 'Out of stock' : 'Add to bag →'}</button><div className="review-section"><h3>Customer reviews</h3>{reviewsLoading ? <LoadingState text="Loading reviews…" /> : reviewsError ? <p className="form-error" role="alert">{reviewsError} <button className="button secondary" onClick={loadReviews}>Retry</button></p> : reviews.length ? reviews.map((review) => <article key={review.id}><strong>{review.customer}</strong><span>{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</span><p>{review.comment}</p></article>) : <p className="empty">No reviews yet. Delivered customers can be the first to share feedback.</p>}<form className="review-form" onSubmit={submitReview}><label>Rate this product<select value={rating} onChange={(event) => setRating(Number(event.target.value))}>{[5, 4, 3, 2, 1].map((value) => <option value={value} key={value}>{value} star{value > 1 ? 's' : ''}</option>)}</select></label><textarea aria-label="Your product review" value={comment} onChange={(event) => setComment(event.target.value)} minLength="3" placeholder="Share your experience after delivery" required /><button className="review-submit" disabled={sending}>{sending ? 'Sending…' : 'Submit review'}</button>{reviewMessage && <p className="review-message">{reviewMessage}</p>}</form></div></div></Modal>;
}
